#
# Makefile for greycstoration.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

#MODULE_PACKAGE=Extensions
MODULE_NAME=greycstoration
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_GREYCStoration.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

MODULE_INCL="$(DEPTH)/contrib/sources/cimg"

include $(DEPTH)/config/rules.mk
