#
# Makefile for storagemap
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=storagemap
MODULE_EXT=cci
MODULE_FILES=CCI_StorageMap.cpp
MODULE_INCL = $(DEPTH)/daim_matrix/include

DAIM_UTILITIES:=1

include $(DEPTH)/config/rules.mk

