#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=binarymorph

MODULE_FILES=cciBinaryMorphology.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIBinaryMorphology.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(DEPTH)/config/rules.mk
