#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=measures

MODULE_FILES=cciMeasurements.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIMeasurements.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(DEPTH)/config/rules.mk
