#-----------------------------------------------------
# Makefile for binarymath.cci
#-----------------------------------------------------

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=binarymath
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_BinaryMath.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1
PURE_DAIM:=1

include $(DEPTH)/config/rules.mk
