/*
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# The Original Code is Daim code.
#
# The Initial Developer of the Original Code is
#   David Marteau
# Portions created by the Initial Developer are Copyright (C) 2008
# the Initial Developer. All Rights Reserved.
#
# Contributor(s):
#   David Marteau (dhmarteau@gmail.com);
#
# Alternatively, the contents of this file may be used under the terms of
# either of the GNU General Public License Version 2 or later (the "GPL"),
# or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
#
# ***** END LICENSE BLOCK *****
*/

#include "cciIKernelFamily.idl"

/**
 * @ingroup daim_interfaces
 *
 * @brief Interface for scriptable kernel family
 *
 * This interface provides methods for implementing
 * new kernel definition
 */
[scriptable, uuid(d43dd7fe-3353-4d10-bde9-26478db0eece)]
interface cciIScriptableKernelFamily : cciIKernelFamily
{
  /**
   * Set a new description of the kernel family
   */
  void newDescription( in long x,
                       in long y,
                       in long width,
                       in long height,
                       in string mode );

  /**
   * Add a new kernel data for the the family
   */
  void addKernel( in string data );

  /**
   * Add a new full kernel description (used for
   * composition of different kernel size
   */
  void addKernelDescription( in string data,
                             in long x,
                             in long y,
                             in long width,
                             in long height );

  /**
   * @brief Clear all data for that family
   */
  void clear();

  cciIKernelFamily clone();

};


%{C++

#define CCI_SCRIPTABLEKERNELFAMILY_CID \
{ /* B3E2CD87-5CAC-4378-8A0B-1A36AC33C678 */       \
  0xB3E2CD87,                                      \
  0x5CAC,                                          \
  0x4378,                                          \
  {0x8A, 0x0B, 0x1A, 0x36, 0xAC, 0x33, 0xC6, 0x78} \
}

#define CCI_SCRIPTABLEKERNELFAMILY_CONTRACTID "@daim.org/scriptable-kernel-family;1"
#define CCI_SCRIPTABLEKERNELFAMILY_CLASSNAME  "Scriptable kernel family"

%}

