#

DEPTH= ../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim

IDLSRC = ccidaim.idl \
         cciIImageList.idl \
         cciISurface.idl \
         cciIDaimService.idl \
         cciIMatrix.idl \
         cciIMetaDataContainer.idl \
         cciIImageContainer.idl \
         cciIRegionContainer.idl \
         cciIRegion.idl \
         cciIMetaDataProvider.idl \
         $(NULL)

DIRS = processing

EXPORTS = cciIImageListContainer.h

include $(DEPTH)/config/rules.mk
