#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=imgmath

MODULE_FILES=cciImageMath.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIImageMath.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(DEPTH)/config/rules.mk
