#
# Makefile for propertylist
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=propertylist
MODULE_EXT=cci
MODULE_FILES=CCI_PropertyList.cpp

DAIM_UTILITIES:=1

include $(DEPTH)/config/rules.mk

