#
# Makefile for daim_kernel dll
#

DEPTH= ../..

include $(DEPTH)/config/config.mk

MODULE_NAME  = daim

EXPORTS = dmKernelBase.h \
          dmImageData.h \
          dmPixelFormats.h \
          dmRGBColor.h \
          dmOperators.h \
          dmCoordinatesTypes.h \
          $(NULL)

include $(topsrcdir)/config/rules.mk


