
DEPTH=../..

include $(DEPTH)/config/config.mk

MODULE_NAME  = utils
LIBRARY_NAME = printimagedata
MODULE_EXT   = exe

MODULE_FILES=printimagedata.cpp

REQUIRES=cci daim contrib

MODULE_LIBS = -lcciglue_s

DAIM_LIB:=1

include $(DEPTH)/config/rules.mk
