#-----------------------------------------------------
# Makefile for cachemngr
#-----------------------------------------------------

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=cachemngr
MODULE_EXT=cci
MODULE_FILES=CCI_Snapshot.cpp \
             dmSnapshot.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1
PURE_DAIM:=1

include $(DEPTH)/config/rules.mk
