#
# Makefile for pngdecode.exe
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=pngdecode
MODULE_EXT=exe
MODULE_FILES=pngdecode.cpp

MODULE_LIBS=-lpng_s -lz_s

MODULE_INCL="$(DEPTH)/contrib/include"

include $(DEPTH)/config/rules.mk



