#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=trnsfrms

MODULE_FILES=cciTransforms.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciITransforms.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(DEPTH)/config/rules.mk
