#
# Makefile for edges.cci
#

DEPTH=../../..
VPATH=$(DEPTH)/include/daim_modules/processing

include $(DEPTH)/config/config.mk

MODULE_NAME=edges
MODULE_GROUP=processing/
MODULE_EXT=cci
MODULE_FILES=CCI_Edges.cpp \
             CCI_RGBFunctor.cpp


DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

include $(DEPTH)/config/rules.mk

