#
# Makefile for imageparts.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=imageparts
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_ImageParts.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

include $(DEPTH)/config/rules.mk
