#
# Makefile for pngencode.exe
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=pngencode
MODULE_EXT=exe
MODULE_FILES=pngencode.cpp

MODULE_LIBS=-lpng_s -lz_s

MODULE_INCL="$(DEPTH)/contrib/include"

include $(DEPTH)/config/rules.mk



