#
# Makefile for tlhistogram.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=tlhistogram
MODULE_EXT=cci
MODULE_GROUP=tools/
MODULE_FILES=CCI_ToolHistogram.cpp \
             dmToolHistogram.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1
DAIM_TOOLS:=1

include $(DEPTH)/config/rules.mk
