#-----------------------------------------------------
# Makefile for ldrfactory.cci
#-----------------------------------------------------

DEPTH=../../../

include $(DEPTH)/config/config.mk

MODULE_NAME=ldrfactory
MODULE_EXT=cci
MODULE_FILES=CCI_LoaderFactory.cpp \
             dmModuleLoader.cpp

DAIM_UTILITIES:=1
DAIM_KERNEL:=1
PURE_DAIM:=1

include $(DEPTH)/config/rules.mk
