#

DEPTH= ../../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=measures

MODULE_FILES=cciMeasures.cpp \
             Measures_impl.cpp \
             Nodes_impl.cpp \
             Properties_impl.cpp \
             $(NULL)

IS_COMPONENT=1

DAIM_LIBKERNEL:=1

include $(DEPTH)/config/rules.mk
