#
# Makefile for flatfield.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=flatfield
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_FlatField.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

include $(DEPTH)/config/rules.mk
