#
# Makefile for histograms.cci
#

DEPTH=../../..
VPATH=$(DEPTH)/include/daim_modules/processing

include $(DEPTH)/config/config.mk

MODULE_NAME=histograms
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_Histograms.cpp \
             CCI_RGBFunctor.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

include $(DEPTH)/config/rules.mk
