#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=densityfilters

MODULE_FILES=cciDensityFilters.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIDensityFilters.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(topsrcdir)/config/rules.mk
