#
# Makefile for bmpldr.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=bmpldr
MODULE_EXT=cci
MODULE_GROUP=loaders/
MODULE_FILES=CCI_BMPLoader.cpp

DAIM_UTILITIES:=1
PURE_DAIM:=1

include $(DEPTH)/config/rules.mk
