/*
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# The Original Code is Daim code.
#
# The Initial Developer of the Original Code is
#   David Marteau
# Portions created by the Initial Developer are Copyright (C) 2008
# the Initial Developer. All Rights Reserved.
#
# Contributor(s):
#   David Marteau (dhmarteau@gmail.com);
#
# Alternatively, the contents of this file may be used under the terms of
# either of the GNU General Public License Version 2 or later (the "GPL"),
# or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
#
# ***** END LICENSE BLOCK *****
*/

#include "cciIImageFilter.idl"

interface cciIMatrix;

[scriptable, uuid(11bb5397-ebf9-41fd-a113-e93b70d6e97b)]
interface cciIColorTransforms : cciIImageFilter
{
  /**
   * @brief Set/get the transformation matrix
   */
  attribute cciIMatrix transformMatrix;

};


%{C++

#define CCI_COLORTRANSFORMS_CID \
{ /* 363DE6A0-D184-4AFE-B703-D8F7256E0E74 */       \
  0x363DE6A0,                                      \
  0xD184,                                          \
  0x4AFE,                                          \
  {0xB7, 0x03, 0xD8, 0xF7, 0x25, 0x6E, 0x0E, 0x74} \
}

#define CCI_COLORTRANSFORMS_CLASSNAME  "Color transformations filter and utilities"
#define CCI_COLORTRANSFORMS_CONTRACTID "@daim.org/processing/color-transforms;1"
#define CCI_COLORUTILS_CONTRACTID      "@daim.org/processing/color-utils;1"

%}
