#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=clrtransforms

MODULE_FILES=cciColorTransforms.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIColorTransforms.idl \
         cciIColorUtils.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(topsrcdir)/config/rules.mk
