#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
IS_COMPONENT=1
LIBRARY_NAME=lcnrty

MODULE_FILES=cciLacunarity.cpp \
             $(NULL)

IDLSRC = cciILacunarity.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(topsrcdir)/config/rules.mk
