#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=thrshld
MODULE_INCL=$(DEPTH)/daim/src

MODULE_FILES=cciThreshold.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIThreshold.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(DEPTH)/config/rules.mk
