#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
LIBRARY_NAME=pyramid
MODULE_INCL=$(DEPTH)/daim/src

MODULE_FILES=cciPyramid.cpp \
             $(NULL)

IS_COMPONENT=1

IDLSRC = cciIPyramid.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(topsrcdir)/config/rules.mk
