#
# Makefile for colorspace 
# The variable COLORSPACE is passed in argument of the make command.
#


DEPTH=../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=$(COLORSPACE)
MODULE_EXT=cci
MODULE_GROUP=processing/colorspaces/
MODULE_FILES=$(COLORSPACE).cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

include $(DEPTH)/config/rules.mk




