#
# Makefile for libjpeg routines
#

DEPTH= ../../..

include $(DEPTH)/config/config.mk

# Output distribution in contrib
MOD_PATH=contrib/

MODULE_NAME=jpeg_s
MODULE_EXT =lib

CMODULE_FILES= \
        jcapimin.c jcapistd.c jccoefct.c jccolor.c jcdctmgr.c jchuff.c \
        jcinit.c jcmainct.c jcmarker.c jcmaster.c jcomapi.c jcparam.c \
        jcphuff.c jcprepct.c jcsample.c jctrans.c jdapimin.c jdapistd.c \
        jdatadst.c jdatasrc.c jdcoefct.c jdcolor.c jddctmgr.c jdhuff.c \
        jdinput.c jdmainct.c jdmarker.c jdmaster.c jdmerge.c jdphuff.c \
        jdpostct.c jdsample.c jdtrans.c jerror.c jfdctflt.c jfdctfst.c \
        jfdctint.c jidctflt.c jidctfst.c jidctint.c jidctred.c jquant1.c \
        jquant2.c jutils.c jmemmgr.c jmemansi.c 

CONTRIB_HEADERS= jconfig.h jerror.h jmorecfg.h jpeglib.h

all: module finalizejpeg
	
finalizejpeg:
	@for d in $(CONTRIB_HEADERS); do \
		cp $$d ../../include/; \
	done

include $(DEPTH)/config/rules.mk

