#

DEPTH= ../../..
include $(DEPTH)/config/config.mk

MODULE_NAME=daim

DIRS = KernelManager \
       ColorSpaces \
       Filters \
       BinaryMorphology \
       Histograms \
       DensityFilters \
       ColorTransforms \
       Threshold \
       Pyramid \
       ImageMath \
       Transforms \
       Results \
       Measures \
       Lacunarity \
       Profile \
       Partition \
       Flatfield \
       $(NULL)

include $(topsrcdir)/config/rules.mk
