#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim
IS_COMPONENT=1
LIBRARY_NAME=parttn

MODULE_FILES=cciPartition.cpp \
             $(NULL)

IDLSRC = cciIPartition.idl \
         $(NULL)

DAIM_LIBKERNEL:=1

include $(topsrcdir)/config/rules.mk
