#
# Makefile for imageshift.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=imageshift
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_ImageShift.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1
DAIM_MATRIX:=1

include $(DEPTH)/config/rules.mk
