#
# Makefile for fractals.cci
#

DEPTH=../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=fractals
MODULE_EXT=cci
MODULE_GROUP=processing/
MODULE_FILES=CCI_Fractals.cpp

DAIM_UTILITIES:=1
DAIM_LIBKERNEL:=1
DAIM_KERNEL:=1

include $(DEPTH)/config/rules.mk
