#

DEPTH= ../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim

IDLSRC = cciIDriverProxy.idl   \
         cciISurfaceDriver.idl \
         cciIRemoteSurface.idl \
         cciILoaderService.idl \
         $(NULL)

include $(DEPTH)/config/rules.mk
