#

DEPTH= ../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim

IDLSRC = cciIFilterMask.idl \
         cciIImageFilter.idl \
         cciIKernelFamily.idl \
         cciIKernelFamilyContainer.idl \
         cciIKernelService.idl \
         cciIScriptableKernelFamily.idl \
         cciIColorSpace.idl \
         cciIFilterContext.idl \
         cciIImageShell.idl \
         cciIColorTable.idl \
         $(NULL)

include $(DEPTH)/config/rules.mk
