#

DEPTH= ../../../../..

include $(DEPTH)/config/config.mk

MODULE_NAME=daim

IDLSRC = cciIConvolutionFilter.idl \
         cciILFilter.idl \
         cciIRFilter.idl \
         cciISharpenFilter.idl \
         $(NULL)

include $(topsrcdir)/config/rules.mk
